### ISSUE TITLE
"get_my_inventory" function needed

### ISSUE THREAD

**Issue by kristoferlund** [kristoferlund/holochain-logistics#8]
https://github.com/kristoferlund/holochain-logistics/blob/5de316e8595ce63652ac785189ed1b233c10b942/dna-src/zomes/event/code/src/inventory/handlers.rs#L45

**Comment by zaunders** [comment]
will try to implement get_inventory_by_adress so that we can get any members inventory, then we can just get my address and pass in to get my.
